class_name CardAttributes

enum CLASS { NEUTRAL, MAGE, WARRIOR}
enum TRIBE { NONE, BEAST, MURLOC, DRAGON, PIRATE, DEMON}
enum KEYWORD {NONE, BATTLECRY, DEATHRATTLE, DIVINE_SHIELD, TAUNT}
enum CARDTYPE {SPELL, MINION}
