class_name CardAttributes

enum CLASS { NEUTRAL, MAGE, WARRIOR, PALADIN, WARLOCK, SHAMAN, DRUID, ROUGE, PRIEST, HUNTER}
enum TRIBE { NONE, BEAST, MURLOC, DRAGON, PIRATE, DEMON}
enum KEYWORD {NONE, BATTLECRY, DEATHRATTLE, DIVINE_SHIELD, TAUNT, STEALTH, EVASIVE}
enum CARDTYPE {SPELL, MINION, WEAPON, HERO}
